---
- name: Install and manage dotfiles with Dotbot
  hosts: localhost
  connection: local
  
  vars:
    dotfiles_repo: "git@github.com:kambic/hyprdots.git"
    dotbot_config: "install.conf.yaml"  # Your config file name
    dotbot_bin: "{{ dotfiles_dest }}/dotbot/bin/dotbot"  # Adjust if submodule path differs
    dotfiles_dest: "{{ ansible_facts['env']['HOME'] }}/dotfiles"

  pre_tasks: 
    - name: Update pacman
      become: true
      pacman: 
        update_cache: true
      tags: install
  tasks:
    - include_tasks: tasks/core.yaml
    # - include_tasks: tasks/zsh.yaml
    - include_tasks: tasks/aur.yaml
    # - include_tasks: tasks/dotfiles.yaml
    # - include_tasks: tasks/node.yaml
    - include_tasks: tasks/fonts.yaml
    # - include_tasks: tasks/desktop.yaml
    - include_tasks: tasks/services.yaml
