---
all:
  children:
    desktops:
      hosts:
        pc:
          ansible_host: localhost
          ansible_connection: local
    laptops:
      hosts:
        laptop:
          ansible_host: 192.168.1.100
          ansible_user: your_user
