- name: Create the '$HOME/.ssh' directory if not exists
  ansible.builtin.file:
    path: "/home/{{ ansible_facts['user_id'] }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
